feat: updated readme architecture image
ambianic/ambianic-subscriptions pull request #18
Opened 2021-06-07 18:24 UTC by vickywane

2021-06-08 14:03 UTC, ivelin requested changes
@vickywane this is a nice high level diagram. Only one comment. Clarify "Cloud APIs" to "Ambianic Cloud APIs".

Let's also add sections with the more detailed diagrams with design details of how UI and edge interact with the cloud APIs. These will be useful references in the future as we discuss new features and improvements.

2021-06-10 09:14 UTC, vickywane commented
@ivelin i have updated the image to correct the text, and also show a more detailed relationship between the connected services.

2021-06-10 15:47 UTC, ivelin commented
@vickywane this diagram looks good. However CI fails for some reason.

2021-06-11 14:42 UTC, ivelin approved these changes

2021-06-11 14:42 UTC, merged